### ISSUE TITLE
Test images only get published with "version-arch" tags upon releases

### ISSUE THREAD

**Issue by akalenyu** [kubevirt/containerized-data-importer#3688]
**What happened**:
Test images only get published with `version-arch` tags upon releases, potentially breaking users relying on the `version` for all containers:

![Image](https://github.com/user-attachments/assets/95098065-76f8-4ed8-8261-1e139fafa481)
VS
![Image](https://github.com/user-attachments/assets/4b05a587-db1f-4052-b1c1-904df22667b0)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by akalenyu** [comment]
/cc @dollierp @cfilleke @zhlhahaha 
in case anyone wants to help, unfortunately me and @awels don't have much capacity to debug the bash scripts

**Comment by cfilleke** [comment]
I think @awels and I fixed this since the last release had properly multi-arch manifested with the release tag. Will double check & likely close this issue w reference to the PRs today.

**Comment by akalenyu** [comment]
> I think [@awels](https://github.com/awels) and I fixed this since the last release had properly multi-arch manifested with the release tag. Will double check & likely close this issue w reference to the PRs today.

Hey, did you get a chance to check this?

**Comment by aglitke** [comment]
When looking at https://quay.io/repository/kubevirt/cdi-controller?tab=tags and filtering for a version (eg. 1.62) I can see arch-specific tags and a plain 1.62 multi-arch container so I think this should be resolved now.  @akalenyu could you please confirm and close this issue if we are good now?

**Comment by akalenyu** [comment]
> When looking at https://quay.io/repository/kubevirt/cdi-controller?tab=tags and filtering for a version (eg. 1.62) I can see arch-specific tags and a plain 1.62 multi-arch container so I think this should be resolved now. [@akalenyu](https://github.com/akalenyu) could you please confirm and close this issue if we are good now?

This is still broken for test images (https://quay.io/repository/kubevirt/cdi-func-test-file-host-http?tab=tags).
The "product" images have been fine all along

**Comment by cfilleke** [comment]
There are manifested nightlies, as well as separately tagged images for each arch. This results in twice the storage as necessary being used. In order to save space on quay,  I'll make a PR to  also stop generating these separately tagged images. Thanks for keeping after me about this @akalenyu

**Comment by akalenyu** [comment]
> There are manifested nightlies, as well as separately tagged images for each arch. This results in twice the storage as necessary being used. In order to save space on quay, I'll make a PR to also stop generating these separately tagged images. Thanks for keeping after me about this [@akalenyu](https://github.com/akalenyu)

thanks for looking! actually, this is not what I meant. it seems like specifically test-supporting-containers are not "manifested"
similarly to product-containers like the cdi-importer.

**Comment by cfilleke** [comment]
commenting so the bot does not make this stale again -- I committed to looking and still shall when I have at least a hot minute. Thanks for your patience, guys.
